version: 2
updates:
  - package-ecosystem: "github-actions"
    directories: ["/", "/plugin/templates"]
    schedule:
      interval: "weekly"
    groups:
      checkout:
        patterns: ["actions/checkout"]
        group-by: dependency-name
